PREFIX fx: <http://sparql.xyz/facade-x/ns/>
# Query to extract the CSV files from the local directory.
SELECT ?filePath ?fileName
WHERE 
{
  SERVICE<x-sparql-anything:>{
  	fx:properties fx:location "./EssenFolk".               
    	
	[] a fx:root;
       	   ?mProp ?filePath.
    
    FILTER(CONTAINS(?filePath, ".csv"))
    BIND (replace(replace(?filePath, ".*?\\/",""), ".csv","") as ?fileName) .
  }
}