PREFIX fx: <http://sparql.xyz/facade-x/ns/>
PREFIX fn: <http://jena.apache.org/ARQ/function#>
# Query to extract the music xml files from the local directory.
SELECT ?filePath ?fileName
WHERE 
{
  SERVICE<x-sparql-anything:>{
  	fx:properties fx:location "./musicXMLFiles/AltDeu10".               
    	
	[] a fx:root;
       	   ?mProp ?filePath.
    
    FILTER(CONTAINS(?filePath, ".musicxml")) .
	BIND ( replace( replace ( ?filePath, ".*?\\/","" ), ".musicxml","") as ?fileName) .
  }
}